{
  "schemaVersion": 1,
  "updatedAt": "2026-09-06T23:06:59Z",
  "featuredIds": [
    "telegram",
    "notion",
    "spotify",
    "pubg-mobile",
    "brawl-stars",
    "asphalt-legends"
  ],
  "config": {
    "ads": {
      "enabled": true,
      "appOpenEnabled": true,
      "appOpenAdUnitId": "demo-appopenad-yandex",
      "appOpenMinBackgroundSeconds": 5,
      "appOpenMinIntervalSeconds": 30,
      "bannerEnabled": true,
      "bannerAdUnitId": "demo-banner-yandex",
      "nativeEnabled": true,
      "nativeAdUnitId": "demo-native-app-yandex",
      "nativeListEnabled": true,
      "nativeListAdUnitId": "demo-native-app-yandex",
      "nativeDetailEnabled": true,
      "nativeDetailAdUnitId": "demo-native-app-yandex",
      "rewardedInstallEnabled": true,
      "rewardedAdUnitId": "demo-rewarded-yandex",
      "interstitialEnabled": true,
      "interstitialAdUnitId": "demo-interstitial-yandex",
      "interstitialEveryInstallClicks": 1,
      "useDemoUnitsInDebug": true
    },
    "oneSignal": {
      "enabled": false,
      "appId": "",
      "promptForPermission": false
    },
    "installRedirect": {
      "enabled": false,
      "url": ""
    }
  },
  "items": [
    {
      "id": "telegram",
      "type": "APP",
      "name": "Telegram",
      "developer": "Telegram FZ-LLC",
      "shortDescription": "Быстрый и безопасный мессенджер",
      "description": "Общайтесь в личных и групповых чатах, подписывайтесь на каналы и отправляйте файлы с любого устройства.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=org.telegram.messenger"
    },
    {
      "id": "vk",
      "type": "APP",
      "name": "VK",
      "developer": "VK.com",
      "shortDescription": "Общение, музыка и видео",
      "description": "Социальная платформа для общения с друзьями, просмотра видео, прослушивания музыки и сообществ.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.vkontakte.android"
    },
    {
      "id": "whatsapp",
      "type": "APP",
      "name": "WhatsApp",
      "developer": "WhatsApp LLC",
      "shortDescription": "Личные сообщения и звонки",
      "description": "Отправляйте сообщения, фотографии и документы, совершайте голосовые и видеозвонки через интернет.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.whatsapp"
    },
    {
      "id": "pinterest",
      "type": "APP",
      "name": "Pinterest",
      "developer": "Pinterest",
      "shortDescription": "Идеи и визуальное вдохновение",
      "description": "Находите идеи для дома, стиля, путешествий и творчества, сохраняйте их в тематические доски.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.pinterest"
    },
    {
      "id": "microsoft-365",
      "type": "APP",
      "name": "Microsoft 365",
      "developer": "Microsoft Corporation",
      "shortDescription": "Документы, таблицы и PDF",
      "description": "Работайте с документами Word, таблицами Excel, презентациями PowerPoint и PDF в одном приложении.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow"
    },
    {
      "id": "notion",
      "type": "APP",
      "name": "Notion",
      "developer": "Notion Labs, Inc.",
      "shortDescription": "Заметки, задачи и проекты",
      "description": "Единое пространство для заметок, баз знаний, проектов и совместной работы команды.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=notion.id"
    },
    {
      "id": "todoist",
      "type": "APP",
      "name": "Todoist",
      "developer": "Doist Inc.",
      "shortDescription": "Планировщик задач и привычек",
      "description": "Организуйте личные и рабочие задачи, устанавливайте сроки и поддерживайте ежедневный фокус.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.todoist"
    },
    {
      "id": "google-drive",
      "type": "APP",
      "name": "Google Диск",
      "developer": "Google LLC",
      "shortDescription": "Облачное хранение файлов",
      "description": "Храните файлы в облаке, открывайте их с разных устройств и делитесь папками с другими людьми.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.google.android.apps.docs"
    },
    {
      "id": "yandex-browser",
      "type": "APP",
      "name": "Яндекс Браузер",
      "developer": "Direct Cursus Computer Systems Trading LLC",
      "shortDescription": "Быстрый браузер с защитой",
      "description": "Открывайте сайты, синхронизируйте данные и используйте встроенные инструменты безопасности и перевода.",
      "category": "Инструменты",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.yandex.browser"
    },
    {
      "id": "2gis",
      "type": "APP",
      "name": "2ГИС",
      "developer": "2GIS",
      "shortDescription": "Карты, навигатор и справочник",
      "description": "Ищите организации, стройте маршруты и пользуйтесь подробными картами города онлайн и офлайн.",
      "category": "Инструменты",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=ru.dublgis.dgismobile"
    },
    {
      "id": "google-maps",
      "type": "APP",
      "name": "Google Карты",
      "developer": "Google LLC",
      "shortDescription": "Карты и навигация",
      "description": "Исследуйте места, прокладывайте маршруты и получайте актуальную информацию о дороге и организациях.",
      "category": "Инструменты",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.google.android.apps.maps"
    },
    {
      "id": "files-google",
      "type": "APP",
      "name": "Files by Google",
      "developer": "Google LLC",
      "shortDescription": "Управление файлами и очистка",
      "description": "Быстро находите файлы, освобождайте место и передавайте документы между устройствами.",
      "category": "Инструменты",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files"
    },
    {
      "id": "tradingview",
      "type": "APP",
      "name": "TradingView",
      "developer": "TradingView Inc.",
      "shortDescription": "Графики и анализ рынков",
      "description": "Следите за котировками и изучайте интерактивные графики финансовых инструментов. Не является инвестиционной рекомендацией.",
      "category": "Финансы",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.tradingview.tradingviewapp"
    },
    {
      "id": "paypal",
      "type": "APP",
      "name": "PayPal",
      "developer": "PayPal Mobile",
      "shortDescription": "Платежи и переводы",
      "description": "Управляйте поддерживаемыми платежами и переводами. Доступность функций зависит от региона.",
      "category": "Финансы",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile"
    },
    {
      "id": "binance",
      "type": "APP",
      "name": "Binance",
      "developer": "Binance Inc.",
      "shortDescription": "Инструменты для криптоактивов",
      "description": "Получайте рыночные данные и используйте доступные функции платформы. Криптоактивы связаны с высоким риском.",
      "category": "Финансы",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "18+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.binance.dev"
    },
    {
      "id": "revolut",
      "type": "APP",
      "name": "Revolut",
      "developer": "Revolut Ltd",
      "shortDescription": "Управление личными финансами",
      "description": "Контролируйте расходы и пользуйтесь доступными финансовыми сервисами. Доступность зависит от региона.",
      "category": "Финансы",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.revolut.revolut"
    },
    {
      "id": "spotify",
      "type": "APP",
      "name": "Spotify",
      "developer": "Spotify AB",
      "shortDescription": "Музыка и подкасты",
      "description": "Слушайте музыку, альбомы и подкасты, создавайте плейлисты и находите новые рекомендации.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=com.spotify.music"
    },
    {
      "id": "youtube-music",
      "type": "APP",
      "name": "YouTube Music",
      "developer": "Google LLC",
      "shortDescription": "Музыкальный стриминг",
      "description": "Открывайте официальные треки, альбомы, живые выступления и персональные подборки.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.music"
    },
    {
      "id": "netflix",
      "type": "APP",
      "name": "Netflix",
      "developer": "Netflix, Inc.",
      "shortDescription": "Фильмы и сериалы",
      "description": "Смотрите доступные фильмы, сериалы и документальные проекты на поддерживаемых устройствах.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.netflix.mediaclient"
    },
    {
      "id": "kinopoisk",
      "type": "APP",
      "name": "Кинопоиск",
      "developer": "Direct Cursus Computer Systems Trading LLC",
      "shortDescription": "Кино, сериалы и информация",
      "description": "Выбирайте фильмы и сериалы, изучайте информацию об актёрах и смотрите доступный контент.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=ru.kinopoisk"
    },
    {
      "id": "pubg-mobile",
      "type": "GAME",
      "name": "PUBG MOBILE",
      "developer": "Level Infinite",
      "shortDescription": "Королевская битва на мобильном",
      "description": "Сражайтесь на больших картах, собирайте снаряжение и оставайтесь последним выжившим в динамичных матчах.",
      "category": "Экшен",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "16+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=com.tencent.ig"
    },
    {
      "id": "cod-mobile",
      "type": "GAME",
      "name": "Call of Duty: Mobile",
      "developer": "Activision Publishing, Inc.",
      "shortDescription": "Сетевой шутер",
      "description": "Участвуйте в соревновательных сетевых режимах и масштабных королевских битвах.",
      "category": "Экшен",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "16+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter"
    },
    {
      "id": "brawl-stars",
      "type": "GAME",
      "name": "Brawl Stars",
      "developer": "Supercell",
      "shortDescription": "Быстрые командные сражения",
      "description": "Выбирайте бойца и участвуйте в коротких командных матчах с разными целями и режимами.",
      "category": "Экшен",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=com.supercell.brawlstars"
    },
    {
      "id": "standoff-2",
      "type": "GAME",
      "name": "Standoff 2",
      "developer": "AXLEBOLT LTD",
      "shortDescription": "Тактический онлайн-шутер",
      "description": "Соревнуйтесь в командных матчах, осваивайте оружие и улучшайте навыки в разных режимах.",
      "category": "Экшен",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "16+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.axlebolt.standoff2"
    },
    {
      "id": "candy-crush",
      "type": "GAME",
      "name": "Candy Crush Saga",
      "developer": "King",
      "shortDescription": "Яркие головоломки три-в-ряд",
      "description": "Собирайте комбинации, проходите уровни и открывайте новые игровые механики.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.king.candycrushsaga"
    },
    {
      "id": "subway-surfers",
      "type": "GAME",
      "name": "Subway Surfers",
      "developer": "SYBO Games",
      "shortDescription": "Бесконечный красочный раннер",
      "description": "Уворачивайтесь от препятствий, собирайте награды и открывайте персонажей и доски.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf"
    },
    {
      "id": "roblox",
      "type": "GAME",
      "name": "Roblox",
      "developer": "Roblox Corporation",
      "shortDescription": "Миллионы пользовательских миров",
      "description": "Исследуйте созданные сообществом миры, играйте с друзьями и создавайте собственные приключения.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.roblox.client"
    },
    {
      "id": "talking-tom",
      "type": "GAME",
      "name": "Мой говорящий Том",
      "developer": "Outfit7 Limited",
      "shortDescription": "Виртуальный питомец",
      "description": "Заботьтесь о Томе, играйте в мини-игры и открывайте одежду и предметы для дома.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.outfit7.mytalkingtomfree"
    },
    {
      "id": "monument-valley",
      "type": "GAME",
      "name": "Monument Valley",
      "developer": "ustwo games",
      "shortDescription": "Архитектурная головоломка",
      "description": "Проведите героиню через невозможные сооружения и оптические иллюзии в спокойном путешествии.",
      "category": "Головоломки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley"
    },
    {
      "id": "cut-the-rope",
      "type": "GAME",
      "name": "Cut the Rope",
      "developer": "ZeptoLab",
      "shortDescription": "Физические головоломки",
      "description": "Перерезайте верёвки, используйте физику и помогайте Ам Няму добраться до конфеты.",
      "category": "Головоломки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.zeptolab.ctr.ads"
    },
    {
      "id": "brain-out",
      "type": "GAME",
      "name": "Brain Out",
      "developer": "Focus apps",
      "shortDescription": "Необычные логические задачи",
      "description": "Решайте задачи с неожиданными ответами и проверяйте внимательность и нестандартное мышление.",
      "category": "Головоломки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.mind.quiz.brain.out"
    },
    {
      "id": "sudoku",
      "type": "GAME",
      "name": "Sudoku.com",
      "developer": "Easybrain",
      "shortDescription": "Классическая числовая головоломка",
      "description": "Решайте судоку разной сложности, используйте заметки и отслеживайте ежедневный прогресс.",
      "category": "Головоломки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.easybrain.sudoku.android"
    },
    {
      "id": "clash-of-clans",
      "type": "GAME",
      "name": "Clash of Clans",
      "developer": "Supercell",
      "shortDescription": "Стройте деревню и сражайтесь",
      "description": "Развивайте деревню, создавайте армию, вступайте в клан и участвуйте в стратегических сражениях.",
      "category": "Стратегии",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.supercell.clashofclans"
    },
    {
      "id": "clash-royale",
      "type": "GAME",
      "name": "Clash Royale",
      "developer": "Supercell",
      "shortDescription": "Тактические карточные дуэли",
      "description": "Собирайте колоду, защищайте башни и сражайтесь с игроками в быстрых матчах реального времени.",
      "category": "Стратегии",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.supercell.clashroyale"
    },
    {
      "id": "pvz2",
      "type": "GAME",
      "name": "Plants vs. Zombies 2",
      "developer": "ELECTRONIC ARTS",
      "shortDescription": "Защита сада от зомби",
      "description": "Собирайте растения и создавайте защиту на уровнях в разных эпохах и игровых мирах.",
      "category": "Стратегии",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.ea.game.pvz2_row"
    },
    {
      "id": "lords-mobile",
      "type": "GAME",
      "name": "Lords Mobile",
      "developer": "IGG.COM",
      "shortDescription": "Глобальная стратегия",
      "description": "Развивайте королевство, собирайте героев и участвуйте в сражениях и союзах игроков.",
      "category": "Стратегии",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.igg.android.lordsmobile"
    },
    {
      "id": "asphalt-legends",
      "type": "GAME",
      "name": "Asphalt Legends",
      "developer": "Gameloft SE",
      "shortDescription": "Аркадные гонки на суперкарах",
      "description": "Собирайте автомобили, участвуйте в динамичных заездах и соревнуйтесь в сетевых режимах.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": true,
      "installUrl": "https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM"
    },
    {
      "id": "fc-mobile",
      "type": "GAME",
      "name": "EA SPORTS FC Mobile",
      "developer": "ELECTRONIC ARTS",
      "shortDescription": "Мобильный футбольный симулятор",
      "description": "Создавайте футбольную команду и участвуйте в матчах, событиях и соревновательных режимах.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.ea.gp.fifamobile"
    },
    {
      "id": "efootball",
      "type": "GAME",
      "name": "eFootball",
      "developer": "KONAMI",
      "shortDescription": "Футбол на мобильном",
      "description": "Собирайте любимых игроков, настраивайте тактику и играйте матчи с соперниками онлайн.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=jp.konami.pesam"
    },
    {
      "id": "hill-climb-racing",
      "type": "GAME",
      "name": "Hill Climb Racing",
      "developer": "Fingersoft",
      "shortDescription": "Весёлые гонки по холмам",
      "description": "Управляйте машинами на сложных трассах, собирайте монеты и улучшайте транспорт.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.fingersoft.hillclimb"
    },
    {
      "id": "instagram",
      "type": "APP",
      "name": "Instagram",
      "developer": "Instagram",
      "shortDescription": "Фото, видео и общение",
      "description": "Делитесь фотографиями и короткими видео, смотрите публикации и общайтесь с друзьями.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.instagram.android"
    },
    {
      "id": "tiktok",
      "type": "APP",
      "name": "TikTok",
      "developer": "TikTok Pte. Ltd.",
      "shortDescription": "Короткие видео и творчество",
      "description": "Смотрите короткие видео, находите авторов и создавайте собственные ролики с эффектами.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically"
    },
    {
      "id": "discord",
      "type": "APP",
      "name": "Discord",
      "developer": "Discord Inc.",
      "shortDescription": "Чаты, сообщества и звонки",
      "description": "Общайтесь в текстовых и голосовых каналах, создавайте сообщества и оставайтесь на связи.",
      "category": "Общение",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.discord"
    },
    {
      "id": "zoom",
      "type": "APP",
      "name": "Zoom Workplace",
      "developer": "zoom.us",
      "shortDescription": "Видеовстречи и совместная работа",
      "description": "Подключайтесь к видеовстречам, переписывайтесь и совместно работайте с мобильного устройства.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=us.zoom.videomeetings"
    },
    {
      "id": "dropbox",
      "type": "APP",
      "name": "Dropbox",
      "developer": "Dropbox, Inc.",
      "shortDescription": "Облако и обмен файлами",
      "description": "Храните документы и фотографии в облаке, синхронизируйте их и делитесь ссылками.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.dropbox.android"
    },
    {
      "id": "google-keep",
      "type": "APP",
      "name": "Google Keep",
      "developer": "Google LLC",
      "shortDescription": "Заметки и списки",
      "description": "Записывайте идеи, создавайте списки и напоминания, синхронизированные между устройствами.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.google.android.keep"
    },
    {
      "id": "microsoft-teams",
      "type": "APP",
      "name": "Microsoft Teams",
      "developer": "Microsoft Corporation",
      "shortDescription": "Рабочие чаты и встречи",
      "description": "Проводите встречи, общайтесь с командой и работайте с общими файлами и каналами.",
      "category": "Продуктивность",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.microsoft.teams"
    },
    {
      "id": "shazam",
      "type": "APP",
      "name": "Shazam",
      "developer": "Apple Inc.",
      "shortDescription": "Распознавание музыки",
      "description": "Определяйте играющие рядом песни, сохраняйте историю и открывайте исполнителей.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.shazam.android"
    },
    {
      "id": "vlc",
      "type": "APP",
      "name": "VLC for Android",
      "developer": "Videolabs",
      "shortDescription": "Универсальный медиаплеер",
      "description": "Воспроизводите видео и аудио разных форматов, локальные файлы и сетевые потоки.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=org.videolan.vlc"
    },
    {
      "id": "twitch",
      "type": "APP",
      "name": "Twitch",
      "developer": "Twitch Interactive, Inc.",
      "shortDescription": "Прямые эфиры и сообщества",
      "description": "Смотрите игровые и творческие трансляции, следите за авторами и общайтесь в чате.",
      "category": "Развлечения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=tv.twitch.android.app"
    },
    {
      "id": "amazon-shopping",
      "type": "APP",
      "name": "Amazon Shopping",
      "developer": "Amazon Mobile LLC",
      "shortDescription": "Поиск и покупка товаров",
      "description": "Ищите товары, сравнивайте предложения и управляйте заказами в поддерживаемых регионах.",
      "category": "Покупки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping"
    },
    {
      "id": "duolingo",
      "type": "APP",
      "name": "Duolingo",
      "developer": "Duolingo",
      "shortDescription": "Изучение языков",
      "description": "Практикуйте языки короткими интерактивными уроками и поддерживайте ежедневную серию.",
      "category": "Образование",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.duolingo"
    },
    {
      "id": "minecraft",
      "type": "GAME",
      "name": "Minecraft",
      "developer": "Mojang",
      "shortDescription": "Стройте и исследуйте миры",
      "description": "Создавайте постройки, исследуйте процедурные миры и играйте в творческом режиме или выживании.",
      "category": "Приключения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.mojang.minecraftpe"
    },
    {
      "id": "genshin-impact",
      "type": "GAME",
      "name": "Genshin Impact",
      "developer": "COGNOSPHERE PTE. LTD.",
      "shortDescription": "Открытый фэнтезийный мир",
      "description": "Исследуйте большой мир, собирайте команду персонажей и участвуйте в динамичных сражениях.",
      "category": "Приключения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact"
    },
    {
      "id": "mobile-legends",
      "type": "GAME",
      "name": "Mobile Legends: Bang Bang",
      "developer": "MOONTON",
      "shortDescription": "Командные сражения 5 на 5",
      "description": "Выбирайте героя, координируйтесь с командой и сражайтесь в быстрых сетевых матчах.",
      "category": "Экшен",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.mobile.legends"
    },
    {
      "id": "among-us",
      "type": "GAME",
      "name": "Among Us",
      "developer": "Innersloth LLC",
      "shortDescription": "Командная игра с предателем",
      "description": "Выполняйте задания на корабле, обсуждайте события и вычисляйте скрытого предателя.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.innersloth.spacemafia"
    },
    {
      "id": "gardenscapes",
      "type": "GAME",
      "name": "Gardenscapes",
      "developer": "Playrix",
      "shortDescription": "Головоломки и восстановление сада",
      "description": "Проходите уровни три-в-ряд, открывайте зоны и создавайте сад вместе с персонажами.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.playrix.gardenscapes"
    },
    {
      "id": "homescapes",
      "type": "GAME",
      "name": "Homescapes",
      "developer": "Playrix",
      "shortDescription": "Головоломки и дизайн дома",
      "description": "Решайте уровни три-в-ряд и обновляйте комнаты семейного дома, открывая историю героев.",
      "category": "Казуальные",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.playrix.homescapes"
    },
    {
      "id": "royal-match",
      "type": "GAME",
      "name": "Royal Match",
      "developer": "Dream Games, Ltd.",
      "shortDescription": "Королевские головоломки",
      "description": "Комбинируйте элементы, проходите уровни и помогайте королю украшать замок.",
      "category": "Головоломки",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.dreamgames.royalmatch"
    },
    {
      "id": "pokemon-go",
      "type": "GAME",
      "name": "Pokémon GO",
      "developer": "Niantic, Inc.",
      "shortDescription": "Исследуйте мир с покемонами",
      "description": "Находите покемонов на карте, участвуйте в рейдах и исследуйте реальные места.",
      "category": "Приключения",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo"
    },
    {
      "id": "hearthstone",
      "type": "GAME",
      "name": "Hearthstone",
      "developer": "Blizzard Entertainment, Inc.",
      "shortDescription": "Коллекционная карточная стратегия",
      "description": "Собирайте колоды, осваивайте героев и участвуйте в пошаговых карточных матчах.",
      "category": "Стратегии",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.blizzard.wtcg.hearthstone"
    },
    {
      "id": "real-racing-3",
      "type": "GAME",
      "name": "Real Racing 3",
      "developer": "ELECTRONIC ARTS",
      "shortDescription": "Реалистичные мобильные гонки",
      "description": "Участвуйте в заездах на лицензированных автомобилях и трассах в разных режимах.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "3+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.ea.games.r3_row"
    },
    {
      "id": "nfs-no-limits",
      "type": "GAME",
      "name": "Need for Speed: No Limits",
      "developer": "ELECTRONIC ARTS",
      "shortDescription": "Уличные гонки и тюнинг",
      "description": "Собирайте автомобили, настраивайте их и участвуйте в динамичных уличных заездах.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "7+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.ea.game.nfs14_row"
    },
    {
      "id": "8-ball-pool",
      "type": "GAME",
      "name": "8 Ball Pool",
      "developer": "Miniclip.com",
      "shortDescription": "Онлайн-бильярд",
      "description": "Играйте в бильярд один на один, участвуйте в турнирах и открывайте новые кии и столы.",
      "category": "Гонки и спорт",
      "iconUrl": "",
      "coverUrl": "",
      "screenshots": [],
      "version": "Актуальная",
      "size": "Зависит от устройства",
      "ageRating": "12+",
      "featured": false,
      "installUrl": "https://play.google.com/store/apps/details?id=com.miniclip.eightballpool"
    }
  ]
}
